name: CI

on: [push, pull_request]

jobs:
  build-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install g++
        run: sudo apt-get update -y && sudo apt-get install -y g++
      - name: Build & run ring-buffer test
        run: |
          g++ -std=c++17 -O2 lockfree_ringbuffer/test_ring_buffer.cpp -o rb
          ./rb

  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cargo test
        run: cargo test --manifest-path orderbook_engine/Cargo.toml --release

  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Vet & build UDP handler
        working-directory: ./udp_feed_handler
        run: |
          go vet .
          go build -v .
